### ISSUE TITLE
Time send is in ms instead s

### ISSUE THREAD

**Issue by lunarok** [mysensors/Arduino#114]
Hi,

Line 367 you have var payload = new Date().getTime();
getTime is reported to be in ms, not in s.
The serial API describe Time as send in s.

Is this a bug in the nodejs or in the API page description ?

This has been reported by a Jeedom user, and as I'm using a fork of this controller, I will like to first report it and have your advice.

Thanks,

Cédric

**Comment by henrikekblad** [comment]
It is a bug in the nodejs controller. Should be new Date().getTime()/1000.

**Comment by lunarok** [comment]
Ok, thanks, I have correct it in the Jeedom plugin

2015-05-24 22:34 GMT+02:00 Henrik Ekblad <notifications@github.com>:
