### ISSUE TITLE
Restyling patch not received

### ISSUE THREAD

**Issue by SinishaDjukic** [mysensors/Arduino#1419]
Dear all,

I've opened a PR, but haven't received the restyling patch, hence further validation also halts:
https://github.com/mysensors/MySensors/pull/1418

I've amended from business to personal mail, but no mail notification either. Any ideas? Thanks!

**Comment by tekka007** [comment]
The email address doesn't appear in the author field, we'll double check the CI scripts.

Here is your restyling patch: https://ci.mysensors.org/job/MySensors/job/MySensors/job/PR-1418/3/The_20Butler_20report/restyling.patch

**Comment by SinishaDjukic** [comment]
Thanks!
In the meantime I checked the build scripts for astyle options used and ran it locally to fix the styling.
