### ISSUE TITLE
Example for Ethernet Gateway 

### ISSUE THREAD

**Issue by sidey79** [mysensors/Arduino#146]
Hi,

in the example Sketch for the Ethernet Gateway is a small Bug. Pins for CE and SS are defined:

#define RADIO_CE_PIN 5 // radio chip enable
#define RADIO_SPI_SS_PIN 6 // radio SPI serial select

But when initializing the Transport object, default pins are used:

MyTransportNRF24 transport(RF24_CE_PIN, RF24_CS_PIN, RF24_PA_LEVEL_GW); 

This shoud be changed to
MyTransportNRF24 transport(RADIO_CE_PIN,RADIO_SPI_SS_PIN, RF24_PA_LEVEL_GW); 

Otherwise, people using different pins, must find that error.

Also it is  better to not define variables for the preprocessor, if they are not needed there.  Use const uint8_t RADIO_CE_PIN =5 ; will clearly create that variable once using one byte of ram.

**Comment by henrikekblad** [comment]
Thanks! 

I didn't quite get the last thing here:

>Also it is better to not define variables for the preprocessor, if they are not needed there. Use const uint8_t RADIO_CE_PIN =5 ; will clearly create that variable once using one byte of ram.

Could you open a separate issue on that one explaining what you want to be changed?
