### ISSUE TITLE
Solution requested for integrating Mysensors with other system

### ISSUE THREAD

**Issue by garudaonekh** [mysensors/Arduino#1474]
Hello,
Currently, I am using Hardware Controller System for Hydroponics running on RPI. I want to add support for many wireless sensors(up to 50) and I want to use MySensors + its gateway but I don't want to use another controller.

My immediate solution is asking my current System to contact with MySensor Gateway thru Py MySensorGateway( https://github.com/theolind/pymysensors) without installing MySensor supported Controller.

Thanks;

**Comment by henrikekblad** [comment]
Please use our forum for discussions.
