### ISSUE TITLE
Dead Project

### ISSUE THREAD

**Issue by jstoaks2112** [mysensors/Arduino#1542]
This project continues to die slowly day after day...

It will soon be discarded from the Home assistant repo as it is not keeping up with changes.

**Comment by tbowmo** [comment]
It's not dead, as you see in [insights](https://github.com/mysensors/MySensors/pulse/monthly)

MySensors has a defined protocol, that is used by many home automation products, including Home Assistant, but the integration into these different automation platforms, is out of scope for the core MySensors project.
