### ISSUE TITLE
ESP8266 Arduino Core 2.0.0 and Multiple definitions of abort()

### ISSUE THREAD

**Issue by mannkind** [mysensors/Arduino#275]
### Steps to Replicate
* Upgrade the [ESP8266 Arduino core](https://github.com/esp8266/Arduino) to 2.0.0
* Attempt to compile the example Gateway ESP8266 MQTT Client Sketch.

### What Happens
Compilation fails w/the error `multiple definition of 'abort'`

### Current Work-Arounds
* Revert to the 1.6.5 version of the  ESP8266 Arduino core
* Rename [this function and subsequent calls](https://github.com/mysensors/Arduino/blob/development/libraries/MySensors/core/MyMainESP8266.cpp#L46).   
  **Note:** I have not confirmed this actually *functions* correctly, only that it compiles.

**Comment by henrikekblad** [comment]
Thanks @mannkind, 

Saw reports on the forum. I will have a look right away when I'm back home from a trip.

**Comment by henrikekblad** [comment]
fixed
