### ISSUE TITLE
[Security] signing bypass flaw

### ISSUE THREAD

**Issue by tekka007** [mysensors/Arduino#296]
Messages with ACK-bit enabled bypass signing verification.

**Comment by fallberg** [comment]
Intended behaviour in the context that acks are not supposed to be signed but it was erroneously assumed that acks were simply sent to the caller without further processing. 
The fix for this will be to require acks to be signed (if the receiver of the ACK require this).

**Comment by tekka007** [comment]
Signing ACK is not a bad idea, however, it won't necessarily solve the issue here. The fixes are (1) to not process ACK messages in the library and (2) verify ACK-bit in the callback function before further processing (see SecureActuator sketch). 
We should eventually consider a different way of ACKing a message, i.e. via a designated I_type + full hash of the original message. Let's have a chat about that.

**Comment by Avamander** [comment]
(I just noticed many issues have [SECURITY] in the title, wouldn't it be easier to create a new issue tracker tag and tag the posts with "Security issue"?)

**Comment by fallberg** [comment]
It's just for me to keep track of my backlog. Generally this feature is not used by the MySensors community.

**Comment by fallberg** [comment]
It's not only issues related to security. It is also various work items.

**Comment by fallberg** [comment]
Secure actuator has been "secured" in the sense that ACKs are now not accepted as data carrying messages. See 62f522. I consider the issue fixed with this.
