### ISSUE TITLE
DallasTemperatureSensor example doesn't build with latest Dallas library

### ISSUE THREAD

**Issue by janchrillesen** [mysensors/Arduino#297]
In the latest version (3.7.5) of the DallasTemperature library millisToWaitForConversion() has changed from a public to a private function, so if you update to the latest version, the sketch won't compile

You need to find another way to check if conversion is one

Offending lines are:

int16_t conversionTime = sensors.millisToWaitForConversion(sensors.getResolution());
sleep(conversionTime);

Simply calling setWaitForConversion(1) instead might fix the problem (at least it builds!) - as I understand, the temperature reading will block until conversion is done, when this is set. I don't have any hardware available right now to test

**Comment by Kolbi** [comment]
I'll may have a look into it the next days.
