### ISSUE TITLE
Create example sketches that allow Jenkins to evaluate various configuration combinations

### ISSUE THREAD

**Issue by fallberg** [mysensors/Arduino#320]

**Comment by maxtox** [comment]
Hi,

i have a "good sketch" to test with (i think).

Includes Relay, Max31855, NTC, DigIN, PWM...

This sketch showed that BUG with Values which did not been reinitialized (old value was in parts in place of the new value) see my issue from just before...

if you like i can send it to you!

**Comment by fallberg** [comment]
This particular issue is more about security. And the examples I talk about is for jenkins use. That means compile time testing, not run time testing.

**Comment by maxtox** [comment]
Oh... Sorry!
