### ISSUE TITLE
RFM69 minor code change

### ISSUE THREAD

**Issue by trlafleur** [mysensors/Arduino#360]
In MyConfig.h

Should the #ifdef, be a #ifndev ??

// Enable this if you're running the RFM69HW model
#ifdef MY_IS_RFM69HW
    #define MY_RFM69HW true
#else
    #define MY_RFM69HW false

// Set this to true if you're running the RFM69HW model
#ifndef MY_IS_RFM69HW
    #define MY_RFM69HW false
#endif

**Comment by henrikekblad** [comment]
In sketch you define MY_IS_RFM69HW 

This sets  MY_RFM69HW to true which is used here when initializing radio:
https://github.com/mysensors/Arduino/blob/development/libraries/MySensors/core/MyTransportRFM69.cpp#L25
