### ISSUE TITLE
ESP8266 

### ISSUE THREAD

**Issue by trlafleur** [mysensors/Arduino#361]
in RFM69.h

You may want to put a #elif defined  for ESP8266 at end  ->> #elif defined(ARDUINO_ARCH_ESP8266)
with the else being a processor not define message...

// INT0 on AVRs should be connected to RFM69's DIO0 (ex on ATmega328 it's D2, on ATmega644/1284 it's D2)
#if defined(__AVR_ATmega168__) || defined(__AVR_ATmega328P__) || defined(__AVR_ATmega88) || defined(__AVR_ATmega8__) || defined(__AVR_ATmega88__)
  #define RF69_IRQ_PIN          2
  #define RF69_IRQ_NUM          0
#elif defined(__AVR_ATmega644P__) || defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega2560__)
  #define RF69_IRQ_PIN          2
  #define RF69_IRQ_NUM          2
#elif defined(__AVR_ATmega32U4__)
  #define RF69_IRQ_PIN          3
  #define RF69_IRQ_NUM          0
#else
  // ESP8266 should fall into this category now
  // TODO !! Untested code! Entering unknown territory...
  #define RF69_IRQ_PIN          2
  #define RF69_IRQ_NUM          0
#endif

**Comment by henrikekblad** [comment]
Duplicate https://github.com/mysensors/Arduino/issues/382
