### ISSUE TITLE
ESP8266 TCP GATEWAY BUG

### ISSUE THREAD

**Issue by jyzhkj** [mysensors/Arduino#367]
http://forum.mysensors.org/topic/2835/mysensors-esp8266-gw-with-relay-presentation-relay-not-working-why/2

**Comment by zaphodus** [comment]
I had the same problem as you and I have found a possible solution.
http://forum.mysensors.org/topic/2112/n00b-ethernet-gw-without-nf24/31
https://github.com/zaphodus/Arduino/commit/ce93db73513f1da45637b186787c9b2501e5d882

**Comment by henrikekblad** [comment]
Fixed in https://github.com/mysensors/Arduino/pull/385
