### ISSUE TITLE
Simple sensor debug

### ISSUE THREAD

**Issue by jardelmv** [mysensors/Arduino#384]
Hello! Thanks for the library.
I'm trying to run a example, changing the ID to 1 (or other number), but the ID is always 255 in the debug and in the msg received by the gateway...
![simple sensor debug](https://cloud.githubusercontent.com/assets/1844605/12793668/c843b2f6-ca98-11e5-8e3d-7284e736109c.jpg)

**Comment by henrikekblad** [comment]
The sensors is asking the controller or an id. You can use static id if you don't have a controller. See api.
