### ISSUE TITLE
Mysensors ESP8266 GW with local relay - Presentation relay does not appear on domoticz why?

### ISSUE THREAD

**Issue by fscoelho** [mysensors/Arduino#395]
Dear all,

I am trying to use the ESP8266 with a local attached relay , but it is not recognized by domoticz.
Can someone help on that ?

Here the information log and the ino code:
Please copy and past on the browser the following:
[forum.mysensors.org/topic/2835/mysensors-esp8266-gw-with-relay-presentation-relay-not-working-why/2](url)

could it be that the connection to controller hasn't been initialised when node/gw sends the presentations.

Any solution ?

**Comment by zaphodus** [comment]
This is the same problem as https://github.com/mysensors/Arduino/issues/367 and it was fixed in https://github.com/mysensors/Arduino/pull/385 . Please, try the latest version.
