### ISSUE TITLE
Using Current RFM69 driver

### ISSUE THREAD

**Issue by trlafleur** [mysensors/Arduino#436]
I have started using the newer RFM69 driver from LowPowerLab in 2.0b, this fix my occasional ST-fail issue with this radio and allows me to remove all of my wait(200) after each send. I'm also informed, that it may fixes the problem with the Ethernet gateway sharing of the hardware SPI, but I have not tested yet...

These are the ONLY changes that I made to there files:
In RFM69.cpp
~~~
from:
#include <RFM69.h>
#include <RFM69registers.h>
#include <SPI.h>

To:
#include "RFM69.h"
#include "RFM69registers.h"
#include <SPI.h>
~~~

https://github.com/LowPowerLab/RFM69

**Comment by henrikekblad** [comment]
The comment looks a bit weird (#include <nothing>). 

If you've identified any problems, could you prepare a pull request with the changes?

**Comment by trlafleur** [comment]
I fixed the includes... (did not have the ~~~)
I just replaced the three files in RFM69 folder with the new files from LowPowerLabs, made the two changes, done...

I'm not set up to do PULL request...

**Comment by trlafleur** [comment]
I have all this working now and have 7 devices on it to a serial gateway...
Using new (current) RFM69 driver and RFM69_ATC...
Its interesting to see the power levels change as packets flow...

If I can figure out how to do a PULL request, I will make it happen to 2.0b development branch...

tom
