### ISSUE TITLE
pinIntTrigger should be made volatile

### ISSUE THREAD

**Issue by goulou** [mysensors/Arduino#448]
in MyHwATMega328.c, pinIntTrigger is not declared volatile : this makes the internalSleep function sleep more than expected.

Expected result : when an interrupt happens, the sleep() function should return true immediately
Actual result : the sleep function returns true (correct value), but only once the full time has elapsed

By setting internalSleep volatile, the behaviour is as expected.

Current behaviour might depends on compiler options.

(sorry for not providing a patch, I think it is quite straightforward!)

**Comment by tekka007** [comment]
good catch, thanks for reporting.
