### ISSUE TITLE
ESP IOT net

### ISSUE THREAD

**Issue by mkeyno** [mysensors/Arduino#463]
hi guys , sorry to make issue for my question , I was wondering if you could help me to my idea about IOT project, The idea is using async webserver on AP ESP module and other ESP station enabled sensor devices can send the data and receive the commands from server, the rate of data logging wont be rather than 1 request per second
what do you think about how strategy should I use ? sync or async
what header type? TCP or MQTT
I might add, the ESP AP server host the webpage , which is user can login and watch data or activities
also on net configuration when we intend to add new node to this net , how ESP client introduce itself to ESP AP server and send its information such as IP address, Number of sensor attached , type of sensor,...so after user can configure the sensor on the web page

**Comment by henrikekblad** [comment]
forum.mysensors.org might be a better place for discussions.
