### ISSUE TITLE
Error compiling GatewayESP8266MQTTClient

### ISSUE THREAD

**Issue by supoeric** [mysensors/Arduino#491]
when compile GatewayESP8266MQTTClient, I got error.
#include <core_version.h>:No such file or directory
#include "Schedule.h":No such file or directory

**Comment by CynthiaGreen** [comment]
The latest development commit requires the ESP8266 2.3.0 Framework. 

Even then the sketch compiles but doesn't seem to actually connect to MQTT or run the setup/loop code. 



The output from the gateway is just a bunch of dots:

sta config unchangedf r-80, scandone
...............pm open,type:2 0
....................................................................................................................................................................................................

**Comment by supoeric** [comment]
after update the libraries, I got 
"dhcp client start...
0;255;3;9;TSM:OK
f r0, scandone
................pm open, type:2 0
........................................................"

**Comment by tekka007** [comment]
@supoeric the PR is not merged yet

**Comment by Iodine-** [comment]
Has this been resolved?  I have 2.0 and still get

`connected with xxxxxx, channel 11
dhcp client start...
0;255;3;0;9;TSM:READY
f r0, scandone
...................pm open,type:2 0
.....................................`

and just infinite dots.

**Comment by JohanElmis** [comment]
Hello friend, 

I've been looking for some stuff when by chance I found  that! It's so  sad,  please read ant tell me what you think  <http://shop.954homeloans.com/e4ixwt>

All the best, johan

**Comment by JohanElmis** [comment]
Dear, 

I saw  you last achievements,  and I  think you need to keep up the good work! Here  is  some helpful  information  for you  <http://slopejova.starkmedical.net/e4tab>

johan
