### ISSUE TITLE
Possible missing braces

### ISSUE THREAD

**Issue by hmeyers** [mysensors/Arduino#99]
Hi,

looking at the function MyGateway::setInclusionMode I am wondering if there a missing braces. At least the current ident suggests an intended implementation of:

```
void MyGateway::setInclusionMode(boolean newMode) {
  if (newMode != inclusionMode) {
    inclusionMode = newMode;
    // Send back mode change on serial line to ack command
    serial(PSTR("0;0;%d;0;%d;%d\n"), C_INTERNAL, I_INCLUSION_MODE, inclusionMode?1:0);

    if (inclusionMode) {
      inclusionStartTime = millis();
    }
  }
}
```

**Comment by henrikekblad** [comment]
Yes, looks like a bug.

**Comment by hmeyers** [comment]
As as suggestion:

Get rid of the if completely as in:

```
void MyGateway::setInclusionMode(boolean newMode) {
  inclusionMode = newMode;
  // Send back mode change on serial line to ack command
  serial(PSTR("0;0;%d;0;%d;%d\n"), C_INTERNAL, I_INCLUSION_MODE, inclusionMode?1:0);
  if (inclusionMode) {
    inclusionStartTime = millis();
  }
}
```

Now if a second inclusion mode request will be received it will extend the inclusion mode time. With the old version it will simply be ignored, possibly confusing the user.

**Comment by henrikekblad** [comment]
O, will only fix this in the development-branch for now.
